name: bfc
description: BrainF*ck Compiler
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.17.5 <3.0.0'

dependencies:
  charcode: ^1.3.1
  args: ^2.3.1
  path: ^1.8.2

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.3
